global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docker'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    metrics_path: /grafana/metrics
    static_configs:
      - targets: ['nb-green-ops--grafana:3000']

  # - job_name: 'nb-green-ops--app'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['nb-green-ops--app:4000']




