
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader-sa
  namespace: default

---

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
 name: metrics-reader-sa
 namespace: default
 annotations:
  kubernetes.io/service-account.name: “metrics-reader-sa”

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader-role
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-reader-role
subjects:
- kind: ServiceAccount
  name: metrics-reader-sa
  namespace: default

# kubectl create clusterrolebinding metrics-reader-binding --clusterrole=view --serviceaccount=default:metrics-reader-sa
