# app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-hack-24-app
  namespace: carbon-hack-24
spec:
  selector:
    matchLabels:
      app: carbon-hack-24-app
  replicas: 1
  template:
    metadata:
      labels:
        app: carbon-hack-24-app
    spec:
      containers:
        - name: carbon-hack-24-app
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
              
          image: 'ch24/prom-exporter-server:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4040
              name: http-app
              protocol: TCP
          resources:
            requests:
             memory: "1Gi"
             cpu: "500m"
            limits:
             memory: "2Gi"
             cpu: "1"
          volumeMounts:
          - mountPath: /app/public
            name: data

      volumes:
        - name: data
          emptyDir:
            sizeLimit: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: carbon-hack-24-app
  name: carbon-hack-24-app
  namespace: carbon-hack-24
spec:
  type: NodePort
  ports:
    - port: 4040
      targetPort: 4040
      nodePort: 31000
      name: carbon-hack-24-app
  selector:
    app: carbon-hack-24-app